* Description

This is a customer front end website developed using React, React-Bootstrap, SASS, Redux,  React Router and Webpack. 

* Quick Start

#+BEGIN_SRC javascript
 git clone https://github.com/XiaolinGe/js-website.git
 npm run dev
#+END_SRC


* Techs & Tools

** Webpack


*** Webpack is module bundler, it takes your dependencies, puts them through loaders and outputs browser compatible static assets. All of this is based on configuration.

** SASS/CSS

*** Sass is css preprocessor, it is an extension of CSS that allows you to use variables, nested rules, mixins, inline imports, and more, all with a fully CSS-compatible syntax. 
 

** React/ReactBoostrap

*** React is a javascript library for building user interfaces.

*** React-Bootstrap is a library of reusable front-end components. It is based on React and Bootstrap.

** Flux/Redux

*** Flux is the application architecture for building client-side web applications. It complements React's composable view components by utilizing a unidirectional data flow.

*** Redux is a predictable state container for JavaScript apps.

(Store)          (React)
app state  -->  components        -->    DOM
 ^                                        |
 |                                        v
 reducers <--------------(dispatch action{type:??,action params})
  ((prev state, action)=> next state)

** React Router

*** React-router is a complete routing library for React. It keeps your UI in sync with the URL. 

//** NodeJS

//*** Node.js is a JavaScript runtime built on Chrome's V8 JavaScript engine. Node.js采用事件驱动、异步编程，为网络服务而设计


//** RESTFul APIs




* APIs

** /api/data

| description | Get all the information of the entire website |
|-------------+-----------------------------------------------|
| URL path    | /api/data                                     |
|-------------+-----------------------------------------------|
| URL method  | GET                                           |
|-------------+-----------------------------------------------|

 data structure


#+BEGIN_SRC json
{
    "infos": {
        "name": "1",
        "pobox": "1",
        "district": "1",
        "city": "1,",
        "country": "1",
        "phone": "1",
        "email": "1",
        "logo": "1",
        "wechat": "1"
    },
    "menus": [{"url": "1", "display": "1"} ...],
    "languages": [{"language": "1"} ...],
    "footerMenus": [{"url": "1", "display": "1"} ...],
    "portfolios": [{"url": "1", "image": "1", "title": "1} ...],
    "services": [{"url": "1", "image": "1", "title": "1"} ...],
    "faqs": [{"question": "1", "answer": "1"} ...]
}

#+END_SRC  

